wrapper_cmp_ctrl:
  custom_compiler: gcc
  gen_static_lib: true
  gen_dynamic_lib: true
source_library:
  lib_name: checkpoint
  dyn_lib_file_name: libcheckpoint.so
  dyn_lib_install_name: libcheckpoint.so
  lib_dirs:
    []
  include_files:
    - ../../include/texture_types.h
    - cupti_checkpoint.h
  include_dirs:
    - $lib1/extras/CUPTI/include
    - $lib1/extras/Debugger/include
    - $lib1/targets/x86_64-linux/include
    - $lib1/nvvm/include
    - $lib1/compute-sanitizer/include
    - $config/PrivateHeader/GL
    - $config/PrivateHeader
    - $config/PrivateHeader/KHR
    - $config/PrivateHeader/EGL
    - $cu_ad
  extra_src_files:
    []
  compilation_options:
    macros:
      - NVML_NO_UNVERSIONED_FUNC_DEFS
      - USE_CUDA_RUNTIME=1
      - __BF16_DEFINED__
      - __FP16_DEFINED__
      - __FP8_DEFINED__
    cxx_flags:
      []
    linker_flags:
      - -soname,libcheckpoint.so
      - --no-as-needed -lpthread
      - "--version-script=<(echo \"libcheckpoint.so {global:  *;local:  *;};\")"
      - --default-symver
  api_functions:
    - name: cuptiCheckpointFree
      signature:
        return_type:
          name: CUptiResult
          type_str: CUptiResult {}
        parameters:
          - name: handle
            param_type:
              name: NV::Cupti::Checkpoint::CUpti_Checkpoint
              is_const: true
              is_pointer: true
              type_str: NV::Cupti::Checkpoint::CUpti_Checkpoint * const {}
      has_body: false
      is_in_namespace: true
      body_dependencies:
        []
      attributes:
        []
    - name: cuptiCheckpointRestore
      signature:
        return_type:
          name: CUptiResult
          type_str: CUptiResult {}
        parameters:
          - name: handle
            param_type:
              name: NV::Cupti::Checkpoint::CUpti_Checkpoint
              is_const: true
              is_pointer: true
              type_str: NV::Cupti::Checkpoint::CUpti_Checkpoint * const {}
      has_body: false
      is_in_namespace: true
      body_dependencies:
        []
      attributes:
        []
    - name: cuptiCheckpointSave
      signature:
        return_type:
          name: CUptiResult
          type_str: CUptiResult {}
        parameters:
          - name: handle
            param_type:
              name: NV::Cupti::Checkpoint::CUpti_Checkpoint
              is_const: true
              is_pointer: true
              type_str: NV::Cupti::Checkpoint::CUpti_Checkpoint * const {}
      has_body: false
      is_in_namespace: true
      body_dependencies:
        []
      attributes:
        []
target_library:
  lib_name: ""
  dyn_lib_file_name: libNeedImpl.so
  lib_dirs:
    []
  include_files:
    []
  include_dirs:
    - $ppu/include
  extra_src_files:
    []
  compilation_options:
    macros:
      - CUDA_VERSION_INSTALL=13001
      - __HGGC_API_V3__
    cxx_flags:
      []
    linker_flags:
      []
  api_functions:
    []
api_mappings:
  - source_function: cuptiCheckpointFree
    target_function: ""
    parameter_mapping:
      {}
  - source_function: cuptiCheckpointRestore
    target_function: ""
    parameter_mapping:
      {}
  - source_function: cuptiCheckpointSave
    target_function: ""
    parameter_mapping:
      {}
global_custom_code:
  loader_start: |
    static uint32_t g_profileDomain;

    static const char* g_profileFunctionList[] = {
        "cuptiCheckpointFree",
        "cuptiCheckpointRestore",
        "cuptiCheckpointSave",
    };

    enum checkpointProfileCallbackId {
        checkpoint_TRACE_CBID_cuptiCheckpointFree = 0,
        checkpoint_TRACE_CBID_cuptiCheckpointRestore = 1,
        checkpoint_TRACE_CBID_cuptiCheckpointSave = 2,
    };

    typedef uint32_t (*checkpointRegisterProfileDomain)(const char* domain_name, const char** function_list, uint32_t function_number);
    typedef uint8_t (*checkpointIsProfileCallbackEnabled)(uint32_t domain, uint32_t callback_id);
    typedef void (*checkpointProfileCallbackBegin)(uint32_t domain, uint32_t callback_id);
    typedef void (*checkpointProfileCallbackEnd)(uint32_t domain, uint32_t callback_id);

    struct checkpointProfileHandler {
        checkpointRegisterProfileDomain registerProfileDomain;
        checkpointIsProfileCallbackEnabled isCallbackEnabled;
        checkpointProfileCallbackBegin profileCallbackBegin;
        checkpointProfileCallbackEnd profileCallbackEnd;
    };

    static checkpointProfileHandler g_profileHandler;
    static bool gDirectReturn = false;
    static const char* gLibName = "checkpoint";

    static void InitializeProfileHandler() {
        // get library patch
        const char* profile_tool_library = getenv("WRAPPER_INJECTION_PATH");
        if (profile_tool_library == NULL) {
            return;
        }

        // open profile library
        void* tool_handler = dlopen(profile_tool_library, RTLD_LAZY);
        if (!tool_handler) {
            printf("cannot open the file:%s  with error %s\n", profile_tool_library, dlerror());
            return;
        }

        // init profile handler
        g_profileHandler.registerProfileDomain = reinterpret_cast<checkpointRegisterProfileDomain>(dlsym(tool_handler, "wrapperRegisterProfileDomain"));
        g_profileHandler.isCallbackEnabled = reinterpret_cast<checkpointIsProfileCallbackEnabled>(dlsym(tool_handler, "wrapperIsProfileCallbackEnabled"));
        g_profileHandler.profileCallbackBegin = reinterpret_cast<checkpointProfileCallbackBegin>(dlsym(tool_handler, "wrapperProfileCallbackBegin"));
        g_profileHandler.profileCallbackEnd = reinterpret_cast<checkpointProfileCallbackEnd>(dlsym(tool_handler, "wrapperProfileCallbackEnd"));

        // register profile domain
        if (g_profileHandler.registerProfileDomain != NULL) {
            g_profileDomain = g_profileHandler.registerProfileDomain(gLibName, g_profileFunctionList, sizeof(g_profileFunctionList) / sizeof(g_profileFunctionList[0]));
            if (g_profileDomain == 0) {
                g_profileHandler.isCallbackEnabled = NULL;
            }
        }
    }

  post_dlopen_tgt_lib: |
    InitializeProfileHandler();

  pre_wrapper_call: |
    bool needProfile = g_profileHandler.isCallbackEnabled != NULL &&
            g_profileHandler.isCallbackEnabled(g_profileDomain, checkpoint_TRACE_CBID_$WRAPPER_FUNC_NAME) != 0;
        if (needProfile) {
            g_profileHandler.profileCallbackBegin(g_profileDomain, checkpoint_TRACE_CBID_$WRAPPER_FUNC_NAME);
        }

  post_wrapper_call: |
    if (needProfile) {
            g_profileHandler.profileCallbackEnd(g_profileDomain, checkpoint_TRACE_CBID_$WRAPPER_FUNC_NAME);
        }

