wrapper_cmp_ctrl:
  custom_compiler: gcc
  gen_static_lib: true
  gen_dynamic_lib: true
source_library:
  lib_name: nvperf_target
  dyn_lib_file_name: libnvperf_target.so
  dyn_lib_install_name: libnvperf_target.so
  lib_dirs:
    []
  include_files:
    - ../../include/texture_types.h
    - nvperf_target.h
  include_dirs:
    - $lib1/extras/CUPTI/include
    - $lib1/extras/Debugger/include
    - $lib1/compute-sanitizer/include
    - $lib1/targets/x86_64-linux/include
    - $lib1/nvvm/include
    - $lib2/include
    - $lib3/include
    - $lib4/Interface
    - $config/PrivateHeader/GL
    - $config/PrivateHeader
    - $config/PrivateHeader/KHR
    - $config/PrivateHeader/EGL
    - $cu_ad
  extra_src_files:
    []
  compilation_options:
    macros:
      - NVML_NO_UNVERSIONED_FUNC_DEFS
      - USE_CUDA_RUNTIME=1
      - __BF16_DEFINED__
      - __FP16_DEFINED__
      - __FP8_DEFINED__
    cxx_flags:
      []
    linker_flags:
      - -soname,libnvperf_target.so
      - --no-as-needed -lpthread
  api_functions:
    - name: NVPA_CounterData_GetNumRanges
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pCounterDataImage
            param_type:
              name: uint8_t
              is_pointer: true
              type_str: const uint8_t * {}
          - name: pNumRanges
            param_type:
              name: size_t
              is_pointer: true
              type_str: size_t * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPA_CounterData_GetRangeDescriptions
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pCounterDataImage
            param_type:
              name: uint8_t
              is_pointer: true
              type_str: const uint8_t * {}
          - name: rangeIndex
            param_type:
              name: size_t
              type_str: size_t {}
          - name: numDescriptions
            param_type:
              name: size_t
              type_str: size_t {}
          - name: ppDescriptions
            param_type:
              name: char
              is_pointer: true
              type_str: const char ** {}
          - name: pNumDescriptions
            param_type:
              name: size_t
              is_pointer: true
              type_str: size_t * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPA_Device_GetNames
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: deviceIndex
            param_type:
              name: size_t
              type_str: size_t {}
          - name: ppDeviceName
            param_type:
              name: char
              is_pointer: true
              type_str: const char ** {}
          - name: ppChipName
            param_type:
              name: char
              is_pointer: true
              type_str: const char ** {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPA_GetDeviceCount
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pNumDevices
            param_type:
              name: size_t
              is_pointer: true
              type_str: size_t * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPA_GetProcAddress
      signature:
        return_type:
          name: NVPA_GenericFn
          type_str: NVPA_GenericFn {}
        parameters:
          - name: pFunctionName
            param_type:
              name: char
              is_pointer: true
              type_str: const char * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPA_InitializeTarget
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          []
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_Adapter_GetDeviceIndex
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_Adapter_GetDeviceIndex_Params
              is_pointer: true
              type_str: NVPW_Adapter_GetDeviceIndex_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_Config_GetNumPasses
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_Config_GetNumPasses_Params
              is_pointer: true
              type_str: NVPW_Config_GetNumPasses_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_CounterData_GetNumRanges
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_CounterData_GetNumRanges_Params
              is_pointer: true
              type_str: NVPW_CounterData_GetNumRanges_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_CounterData_GetRangeDescriptions
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_CounterData_GetRangeDescriptions_Params
              is_pointer: true
              type_str: NVPW_CounterData_GetRangeDescriptions_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_Device_GetMigAttributes
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_Device_GetMigAttributes_Params
              is_pointer: true
              type_str: NVPW_Device_GetMigAttributes_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_Device_GetNames
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_Device_GetNames_Params
              is_pointer: true
              type_str: NVPW_Device_GetNames_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_Device_GetPciBusIds
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_Device_GetPciBusIds_Params
              is_pointer: true
              type_str: NVPW_Device_GetPciBusIds_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_GetDeviceCount
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_GetDeviceCount_Params
              is_pointer: true
              type_str: NVPW_GetDeviceCount_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_InitializeTarget
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_InitializeTarget_Params
              is_pointer: true
              type_str: NVPW_InitializeTarget_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_PeriodicSampler_CounterData_GetDelimiters
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_PeriodicSampler_CounterData_GetDelimiters_Params
              is_pointer: true
              type_str: NVPW_PeriodicSampler_CounterData_GetDelimiters_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_PeriodicSampler_CounterData_GetSampleTime
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_PeriodicSampler_CounterData_GetSampleTime_Params
              is_pointer: true
              type_str: NVPW_PeriodicSampler_CounterData_GetSampleTime_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_PeriodicSampler_CounterData_TrimInPlace
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_PeriodicSampler_CounterData_TrimInPlace_Params
              is_pointer: true
              type_str: NVPW_PeriodicSampler_CounterData_TrimInPlace_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_Profiler_CounterData_GetRangeDescriptions
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_Profiler_CounterData_GetRangeDescriptions_Params
              is_pointer: true
              type_str: NVPW_Profiler_CounterData_GetRangeDescriptions_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_SetLibraryLoadPaths
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_SetLibraryLoadPaths_Params
              is_pointer: true
              type_str: NVPW_SetLibraryLoadPaths_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
    - name: NVPW_SetLibraryLoadPathsW
      signature:
        return_type:
          name: NVPA_Status
          type_str: NVPA_Status {}
        parameters:
          - name: pParams
            param_type:
              name: NVPW_SetLibraryLoadPathsW_Params
              is_pointer: true
              type_str: NVPW_SetLibraryLoadPathsW_Params * {}
      has_body: false
      body_dependencies:
        []
      attributes:
        []
target_library:
  lib_name: ""
  dyn_lib_file_name: libNeedImpl.so
  lib_dirs:
    []
  include_files:
    []
  include_dirs:
    - $output/hggc_wrapper
    - $ppu/include
  extra_src_files:
    []
  compilation_options:
    macros:
      - CUDA_VERSION_INSTALL=11021
      - __TEXTURE_DEFINED__
    cxx_flags:
      []
    linker_flags:
      []
  api_functions:
    []
api_mappings:
  - source_function: NVPA_CounterData_GetNumRanges
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPA_CounterData_GetRangeDescriptions
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPA_Device_GetNames
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPA_GetDeviceCount
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPA_GetProcAddress
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPA_InitializeTarget
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_Adapter_GetDeviceIndex
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_Config_GetNumPasses
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_CounterData_GetNumRanges
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_CounterData_GetRangeDescriptions
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_Device_GetMigAttributes
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_Device_GetNames
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_Device_GetPciBusIds
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_GetDeviceCount
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_InitializeTarget
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_PeriodicSampler_CounterData_GetDelimiters
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_PeriodicSampler_CounterData_GetSampleTime
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_PeriodicSampler_CounterData_TrimInPlace
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_Profiler_CounterData_GetRangeDescriptions
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_SetLibraryLoadPaths
    target_function: ""
    parameter_mapping:
      {}
  - source_function: NVPW_SetLibraryLoadPathsW
    target_function: ""
    parameter_mapping:
      {}
global_custom_code:
  loader_start: |
    static uint32_t g_profileDomain;

    static const char* g_profileFunctionList[] = {
        "NVPA_CounterData_GetNumRanges",
        "NVPA_CounterData_GetRangeDescriptions",
        "NVPA_Device_GetNames",
        "NVPA_GetDeviceCount",
        "NVPA_GetProcAddress",
        "NVPA_InitializeTarget",
        "NVPW_Adapter_GetDeviceIndex",
        "NVPW_Config_GetNumPasses",
        "NVPW_CounterData_GetNumRanges",
        "NVPW_CounterData_GetRangeDescriptions",
        "NVPW_Device_GetMigAttributes",
        "NVPW_Device_GetNames",
        "NVPW_Device_GetPciBusIds",
        "NVPW_GetDeviceCount",
        "NVPW_InitializeTarget",
        "NVPW_PeriodicSampler_CounterData_GetDelimiters",
        "NVPW_PeriodicSampler_CounterData_GetSampleTime",
        "NVPW_PeriodicSampler_CounterData_TrimInPlace",
        "NVPW_Profiler_CounterData_GetRangeDescriptions",
        "NVPW_SetLibraryLoadPaths",
        "NVPW_SetLibraryLoadPathsW",
    };

    enum nvperf_targetProfileCallbackId {
        nvperf_target_TRACE_CBID_NVPA_CounterData_GetNumRanges = 0,
        nvperf_target_TRACE_CBID_NVPA_CounterData_GetRangeDescriptions = 1,
        nvperf_target_TRACE_CBID_NVPA_Device_GetNames = 2,
        nvperf_target_TRACE_CBID_NVPA_GetDeviceCount = 3,
        nvperf_target_TRACE_CBID_NVPA_GetProcAddress = 4,
        nvperf_target_TRACE_CBID_NVPA_InitializeTarget = 5,
        nvperf_target_TRACE_CBID_NVPW_Adapter_GetDeviceIndex = 6,
        nvperf_target_TRACE_CBID_NVPW_Config_GetNumPasses = 7,
        nvperf_target_TRACE_CBID_NVPW_CounterData_GetNumRanges = 8,
        nvperf_target_TRACE_CBID_NVPW_CounterData_GetRangeDescriptions = 9,
        nvperf_target_TRACE_CBID_NVPW_Device_GetMigAttributes = 10,
        nvperf_target_TRACE_CBID_NVPW_Device_GetNames = 11,
        nvperf_target_TRACE_CBID_NVPW_Device_GetPciBusIds = 12,
        nvperf_target_TRACE_CBID_NVPW_GetDeviceCount = 13,
        nvperf_target_TRACE_CBID_NVPW_InitializeTarget = 14,
        nvperf_target_TRACE_CBID_NVPW_PeriodicSampler_CounterData_GetDelimiters = 15,
        nvperf_target_TRACE_CBID_NVPW_PeriodicSampler_CounterData_GetSampleTime = 16,
        nvperf_target_TRACE_CBID_NVPW_PeriodicSampler_CounterData_TrimInPlace = 17,
        nvperf_target_TRACE_CBID_NVPW_Profiler_CounterData_GetRangeDescriptions = 18,
        nvperf_target_TRACE_CBID_NVPW_SetLibraryLoadPaths = 19,
        nvperf_target_TRACE_CBID_NVPW_SetLibraryLoadPathsW = 20,
    };

    typedef uint32_t (*nvperf_targetRegisterProfileDomain)(const char* domain_name, const char** function_list, uint32_t function_number);
    typedef uint8_t (*nvperf_targetIsProfileCallbackEnabled)(uint32_t domain, uint32_t callback_id);
    typedef void (*nvperf_targetProfileCallbackBegin)(uint32_t domain, uint32_t callback_id);
    typedef void (*nvperf_targetProfileCallbackEnd)(uint32_t domain, uint32_t callback_id);

    struct nvperf_targetProfileHandler {
        nvperf_targetRegisterProfileDomain registerProfileDomain;
        nvperf_targetIsProfileCallbackEnabled isCallbackEnabled;
        nvperf_targetProfileCallbackBegin profileCallbackBegin;
        nvperf_targetProfileCallbackEnd profileCallbackEnd;
    };

    static nvperf_targetProfileHandler g_profileHandler;
    static bool gDirectReturn = false;
    static const char* gLibName = "nvperf_target";

    static void InitializeProfileHandler() {
        // get library patch
        const char* profile_tool_library = getenv("WRAPPER_INJECTION_PATH");
        if (profile_tool_library == NULL) {
            return;
        }

        // open profile library
        void* tool_handler = dlopen(profile_tool_library, RTLD_LAZY);
        if (!tool_handler) {
            printf("cannot open the file:%s  with error %s\n", profile_tool_library, dlerror());
            return;
        }

        // init profile handler
        g_profileHandler.registerProfileDomain = reinterpret_cast<nvperf_targetRegisterProfileDomain>(dlsym(tool_handler, "wrapperRegisterProfileDomain"));
        g_profileHandler.isCallbackEnabled = reinterpret_cast<nvperf_targetIsProfileCallbackEnabled>(dlsym(tool_handler, "wrapperIsProfileCallbackEnabled"));
        g_profileHandler.profileCallbackBegin = reinterpret_cast<nvperf_targetProfileCallbackBegin>(dlsym(tool_handler, "wrapperProfileCallbackBegin"));
        g_profileHandler.profileCallbackEnd = reinterpret_cast<nvperf_targetProfileCallbackEnd>(dlsym(tool_handler, "wrapperProfileCallbackEnd"));

        // register profile domain
        if (g_profileHandler.registerProfileDomain != NULL) {
            g_profileDomain = g_profileHandler.registerProfileDomain(gLibName, g_profileFunctionList, sizeof(g_profileFunctionList) / sizeof(g_profileFunctionList[0]));
            if (g_profileDomain == 0) {
                g_profileHandler.isCallbackEnabled = NULL;
            }
        }
    }

  post_dlopen_tgt_lib: |
    InitializeProfileHandler();

