
echo "Setup environment for CUDA"
export CUDA_PATH=$SDK_ROOT/CUDA_SDK
export CUDA_HOME=$CUDA_PATH
export CUDA_TOOLKIT_ROOT=$CUDA_PATH
export PATH=$CUDA_PATH/bin:$PATH
export LD_LIBRARY_PATH=$SDK_ROOT/CUDA_SDK/lib64:${LD_LIBRARY_PATH}
export LIBRARY_PATH=$SDK_ROOT/CUDA_SDK/lib64:${LIBRARY_PATH}
